export const fieldValues = {
    typeOfSeller: {
        "Private Seller": 8,
        "Dealer": 10,
        "Maybe Freelancer": 6,
    },
    fuelType: {
        "Gasoline (Petrol)": 10,
        "Diesel": 9,
        "Electricity (EV)": 10,
        "Hybrid (HEV)": 9,
        "Plug-in Hybrid (PHEV)": 8,
        "Compressed Natural Gas (CNG)": 7,
        "Liquefied Petroleum Gas (LPG)": 7,
        "Ethanol (E85, E10)": 6,
        "Biodiesel": 6,
        "Hydrogen (Fuel Cell)": 10,
        "Could'nt Inspect": 0,
    },
    regionalSpecs: {
        "American": 8,
        "Canadian": 9,
        "Korean": 7,
        "Chiniese": 6,
        "GCC": 10,
        "Japanese": 9,
        "European": 10,
    },
    transmission: {
        "Automatic Transmission (AT)": 10,
        "Manual Transmission (MT)": 8,
        "Electric": 10,
        "Continuously Variable Transmission (CVT)": 9,
        "Could'nt Inspect": 0,
    },
    noCylinders: {
        "3-cylinder": 6,
        "4-cylinder": 8,
        "6-cylinder": 9,
        "8-cylinder": 10,
        "10-cylinder": 9,
        "12-cylinder": 8,
        "14-cylinder": 7,
        "16-cylinder": 6,
        "N/A": 0,
    },
    carTitle: {
        "Clean Title": 10,
        "Salvage Title": 2,
        "Rebuilt/Reconstructed Title": 4,
        "Flood Title": 1,
        "Junk Title": 0,
        "Dismantled Title": 0,
        "Lemon Law Title": 3,
        "Odometer Roll Back Title": 2,
        "Bonded Title": 5,
        "Theft Recovery Title": 4,
        "Export Only Title": 6,
        "Parts Only Title": 0,
    },
    carEligible: {
        "Eligible": 10,
        "Not Eligible": 0,
    },
    vehicleType: {
        "Sedan": 8,
        "SUV": 10,
        "Coupe": 7,
        "Hatchback": 6,
        "Convertible": 7,
        "Station Wagon": 6,
        "Motorcycle": 5,
        "Luxury Car": 10,
        "Sports Car": 9,
        "Minivan": 7,
        "Truck": 8,
        "Van": 6,
    },
    driveType: {
        "Front-Wheel Drive (FWD)": 8,
        "Rear-Wheel Drive (RWD)": 7,
        "All-Wheel Drive (AWD)": 10,
        "Four-Wheel Drive (4WD)": 10,
        "Part-Time 4WD": 9,
        "Full-Time 4WD": 10,
        "Electric Drive (EV)": 10,
        "Hybrid Drive": 9,
    },
    interior: {
        "Leather": 10,
        "Fabric": 8,
        "Suede": 9,
        "Couldn't Inspect": 0,
    },
    noKeys: {
        "1": 5,
        "2": 10,
        "3": 10,
        "none": 0,
    },
    spareTire: {
        "Avaiable": 10,
        "Not Available": 0,
        "Couldn't Inspect": 0,
    },
    primaryDamage: {
        "None": 10,
        "Front End": 2,
        "Rear End": 2,
        "Side": 3,
        "Flood": 1,
        "Fire": 1,
        "Hale": 4,
        "Vandalism": 3,
        "Theft": 2,
        "Frame Range": 1,
        "Mechanical": 2,
        "Electircal": 2,
        "Undercarriage": 3,
        "water Damage": 1,
        "Interior Interior": 2,
        "Roof": 3,
    },
    trim: {
        "1": 5,
        "2": 10,
    },
    vehicleCondition: {
        "Run and Drive": 10,
        "Start": 8,
        "Won't Start": 0,
        "Enhanced Vehicles": 5,
        "Stationary": 3,
        "Does not Start": 0,
        "Salvage": 1,
    },
    roofLining: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    engineUpperCover: {
        "Pass": 10,
        "Minor Scratches": 8,
        "Major Scratches": 5,
        "Cracked / Broken": 3,
        "Missing Components": 2,
        "Missing": 0,
        "Other": 1,
    },
    engineShieldCover: {
        "Pass": 10,
        "Minor Scratches": 8,
        "Major Scratches": 5,
        "Cracked / Broken": 3,
        "Missing Components": 2,
        "Missing": 0,
        "Other": 1,
    },
    engineMounts: {
        "Pass": 10,
        "Minor worn out due to wear and tear.Needs to be replaced": 6,
        "Damaged(can lead to engine vibration)": 4,
        "Broken(can lead to engine vibration and clunking noise)": 2,
        "Other": 1,
    },
    bonnetHingeHolder: {
        "Pass": 10,
        "Missing/Unavailable": 0,
        "Not opening smoothly, cable and/or lock needs to be repaired.": 5,
        "Aftermarket": 3,
        "Other": 1,
    },
    turboSupercharger: {
        "Pass": 10,
        "N/A": 0,
        "Fan not working properly": 4,
        "Needs to be serviced": 6,
        "Seal(s) damaged": 3,
        "Hose/clamp damaged": 2,
        "Other": 1,
    },
    fenderLiners: {
        "Pass": 10,
        "Scratched": 8,
        "Minor Damaged/Cracked": 6,
        "Major Damaged/Cracked": 4,
        "Missing clips": 2,
        "Liners missing": 0,
        "Other": 1,
    },
    driveBeltPulleys: {
        "Pass": 10,
        "General wear and tear": 8,
        "Squeaking belt sounds": 6,
        "Damaged bearing": 4,
        "Damaged pulley": 2,
        "Other": 1,
    },
    engineIdle: {
        "Pass": 10,
        "RPM is fluctuating": 6,
        "Idling below normal": 4,
        "Bouncing or shaking during idle": 3,
        "Engine stalling": 2,
        "Vehicle not starting": 0,
        "Other": 1,
    },
    fluidLevelCondition: {
        "Pass": 10,
        "Dark brown, fluid and filter needs to be replaced": 6,
        "Light pinkish fluid, water or fluid contamination. Might mean damaged transmission": 4,
        "Level is low, needs to be topped up with same oil grade": 7,
        "Level is high, needs to be partially removed": 7,
        "Filler cap damaged/broken": 3,
        "Filler cap missing": 0,
        "Other": 1,
    },
    transmissionFluidLeaks: {
        "Pass": 10,
        "Leak from transmission seal": 4,
        "Leak from transmission lines": 3,
        "Leak from transmission pump": 2,
        "Leak from transmission pan": 1,
        "Other": 0,
    },
    gearSelector: {
        "Pass": 10,
        "Scratched": 8,
        "Damaged/Cracked": 6,
        "Missing components": 4,
        "Missing": 0,
        "Aftermarket": 5,
        "Other": 1,
    },
    brakePadsFront: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    brakePadsRear: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    brakeDiscsFront: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    brakeDiscsRear: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    aBSSensors: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    handbrake: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    frontSuspension: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    rearSuspension: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    keyRemote: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    entertainmentSystem: {
        "Pass": 10,
        "Other": 5,
    },
    windowsOperation: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    seatsAdjustment: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    doorLockUnlock: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    aCControlCooling: {
        "Pass": 10,
        "Other": 5,
    },
    centerConsoleButtons: {
        "Pass": 10,
        "Other": 5,
    },
    cameras: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    gauges: {
        "Pass": 10,
        "Other": 5,
    },
    rearViewSideMirrorElectricals: {
        "Pass": 10,
        "Other": 5,
    },
    aCGrilles: {
        "Pass": 10,
        "Other": 5,
    },
    startingIgnitionSystem: {
        "Pass": 10,
        "Other": 5,
    },
    brakeLights: {
        "Pass": 10,
        "Other": 5,
    },
    headlights: {
        "Pass": 10,
        "Other": 5,
    },
    fogLights: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    reverseLights: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    highBeams: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    numberPlateLights: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    indicatorsHazards: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    wipers: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    softClosingDoors: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    sunroofMoonroof: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    interiorLights: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    cruiseControl: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    horn: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    parkingSensors: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    rearViewMirror: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    steeringWheelUpholstery: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    seatsUpholstery: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    gearLever: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    trunkLining: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    armrestSidePockets: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    dashboard: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    floorMats: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    doors: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    frontWindscreen: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
    rearWindscreen: {
        "Pass": 10,
        "N/A": 0,
        "Other": 5,
    },
};